### PR TITLE
ios: UI to translate chat messages

### PR DESCRIPTION
**Pull request by levitatingpineapple**
# Contents

Adds translate sheet to chat item menu.

# Privacy Considerations

While iOS has on-device translation, it is not enabled by default.
On initial use the OS will present a popup, informing user that text for translation will be sent to apple.
We might consider additional prompt, informing that on-device translation can be enabled in:
`Settings -> Translate -> On-Device Mode`

# Screenshots

https://github.com/simplex-chat/simplex-chat/assets/28978251/fc98bfed-edf7-44f5-8ff6-cf4ecbb77381

### CODE REVIEW

**Comment by epoberezkin** [comment]
can we restrict it to on-device?

**Comment by levitatingpineapple** [comment]
> can we restrict it to on-device?

Thats out of our control. 
Best we can do is inform.

**Comment by epoberezkin** [comment]
We should show the alert asking to open the correct settings and configure translations, recommending to enable on-device - is it possible? The alert would have Open settings and Cancel button.

And then not proceed with the translation until the user opens the settings via this alert.

**Comment by levitatingpineapple** [comment]
https://github.com/simplex-chat/simplex-chat/pull/4906

**Pull request closed without merging**
