### PR TITLE
 notification led for new message

### LINKED ISSUE #4029: Notification LED not light up and blink
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Android

### OS version

Android 9

### App version

5.6.1 (193)

### Current Behavior

When the phone display is off and I receive a message, I hear the notification tone, but the notification LED on the phone does not blinking.

It would be nice to be able to adjust the colour within the application...

### Expected Behavior

When I get a message with the display off, don't just play a sound, use the notification LED on the phone. 

### Steps To Reproduce

I don't know if a device specific problem (my device is a Cubot Quest) but if you have on the phone a notification LED see it when you get a message the LED not blinking.

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by psuzn**
Fixes #4029

### CODE REVIEW

**Comment by psuzn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by epoberezkin** [comment]
Thank you!

It is cool, but it will raise objections from some users as something that can compromise privacy - so there should be an option in Notification settings, something like "Show light" (and we can set default to "on" for the new users and "off" for the existing users).

@avently

**Comment by summoner001** [comment]
@epoberezkin 

Couldn't it be possible to set the LED color per profile like in k9 email?

**Comment by summoner001** [comment]
@epoberezkin 

Couldn't it be possible to set the LED color per profile like in k9 email?

**Comment by epoberezkin** [comment]
we don't set most privacy settings per profile, so no need to complicate it - the MVP to release it would be a global in-app setting that would apply to all profiles, because then it won't require any changes in the core - it just requires updating native preferences and adding a simple toggle in the UI.

**Comment by psuzn** [comment]
| Screenshot 2024-04-29 at 19 13 03 | Screenshot 2024-04-29 at 19 25 57|
|-----------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|

**Comment by epoberezkin** [comment]
Great!

I think we should change it to toggle and ship it. The UX convention is to use toggle for options with on/off states.

**Comment by epoberezkin** [comment]
see comment in #4229

**Pull request closed without merging**
