### PR TITLE
fixed install cabal file paths.

### PR DESCRIPTION
**Pull request by andorsk**
Was running into issues around installing via cabal. 

```
exe:simplex-bot-advanced from simplex-chat-5.4.0.7, exe:simplex-bot from
simplex-chat-5.4.0.7 and others). The exception was:
Invalid file name in tar archive:
"simplex-chat-5.4.0.7/apps/simplex-broadcast-bot/src/../"
```
Bad pathing from tar archive due to the cabal file having `..` in the direct `main-is`. This fixes it. 

```
asdf@asdf simplex-chat % cabal install
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/simplex-chat-5.4.0.7.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/http2-4.2.2.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/aeson-2.2.1.0.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/android-support-0.1.0.0.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/direct-sqlcipher-2.3.28.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/terminal-0.2.0.0.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/socks-0.6.1.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/simplexmq-5.4.0.7.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/sqlcipher-simple-0.4.18.1.tar.gz
Wrote tarball sdist to
/Users/asdf/workspace/github.com/AAAAA/ephemeral/simplex-chat/dist-newstyle/sdist/zip-2.0.0.tar.gz
Warning: Requested index-state 2023-10-20T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2023-10-19T23:04:42Z).
Resolving dependencies...
Build profile: -w ghc-9.6.3 -O1
In order, the following will be built (use -v for more details):
 - simplex-chat-5.4.0.7 (lib) (requires build)
 - simplex-chat-5.4.0.7 (exe:simplex-bot-advanced) (requires build)
 - simplex-chat-5.4.0.7 (exe:simplex-broadcast-bot) (requires build)
 - simplex-chat-5.4.0.7 (exe:simplex-bot) (requires build)
 - simplex-chat-5.4.0.7 (exe:simplex-directory-service) (requires build)
 - simplex-chat-5.4.0.7 (exe:simplex-chat) (requires build)
Starting     simplex-chat-5.4.0.7 (lib)
Building     simplex-chat-5.4.0.7 (lib)
Installing   simplex-chat-5.4.0.7 (lib)
Completed    simplex-chat-5.4.0.7 (lib)
Starting     simplex-chat-5.4.0.7 (exe:simplex-bot)
Starting     simplex-chat-5.4.0.7 (exe:simplex-chat)
Starting     simplex-chat-5.4.0.7 (exe:simplex-broadcast-bot)
Starting     simplex-chat-5.4.0.7 (exe:simplex-directory-service)
Starting     simplex-chat-5.4.0.7 (exe:simplex-bot-advanced)
Building     simplex-chat-5.4.0.7 (exe:simplex-directory-service)
Building     simplex-chat-5.4.0.7 (exe:simplex-bot-advanced)
Building     simplex-chat-5.4.0.7 (exe:simplex-broadcast-bot)
Building     simplex-chat-5.4.0.7 (exe:simplex-chat)
Building     simplex-chat-5.4.0.7 (exe:simplex-bot)
Installing   simplex-chat-5.4.0.7 (exe:simplex-bot)
Installing   simplex-chat-5.4.0.7 (exe:simplex-bot-advanced)
Completed    simplex-chat-5.4.0.7 (exe:simplex-bot)
Installing   simplex-chat-5.4.0.7 (exe:simplex-broadcast-bot)
Completed    simplex-chat-5.4.0.7 (exe:simplex-bot-advanced)
Completed    simplex-chat-5.4.0.7 (exe:simplex-broadcast-bot)
Installing   simplex-chat-5.4.0.7 (exe:simplex-chat)
Completed    simplex-chat-5.4.0.7 (exe:simplex-chat)
Installing   simplex-chat-5.4.0.7 (exe:simplex-directory-service)
Completed    simplex-chat-5.4.0.7 (exe:simplex-directory-service)
Symlinking 'simplex-chat' to '/Users/asdf/.cabal/bin/simplex-chat'
Symlinking 'simplex-directory-service' to
'/Users/asdf/.cabal/bin/simplex-directory-service'
Symlinking 'simplex-bot' to '/Users/asdf/.cabal/bin/simplex-bot'
Symlinking 'simplex-broadcast-bot' to
'/Users/asdf/.cabal/bin/simplex-broadcast-bot'
Symlinking 'simplex-bot-advanced' to
'/Users/asdf/.cabal/bin/simplex-bot-advanced'
```

### CODE REVIEW

**Comment by epoberezkin** [comment]
Thank you!

We use hpack (cabal install hpack-0.35), so the change needs to be in package.yaml and then .cabal file updated with hpack...

But that's cool if it's possible, I didn't figure out a way to make it both build independently and used in tests... Possibly exactly hpack was the reason?

**Comment by andorsk** [comment]
@epoberezkin fixed package.yaml

**Comment by epoberezkin** [comment]
The problem here is that .cabal is (should be) autogenerated from package.yaml, and with the current package.yaml .cabal file will have source dir at apps/simplex-directory-service/src, so `cabal install` will still don't work.

And if you remove /src from package.yaml source, then hpack will remove source files there from .cabal, and it won't even work.

I am not sure if the configuration we need is even possible with hpack/package.yaml, possible there is some combination of parameters in package.yaml that will produce the .cabal file we need... Or maybe we're hitting some limitation of hpack format, and the only way to solve it is to drop hpack entirely.

In any case, as is it won't work, as the current .cabal file will be different when you run hpack.

**Comment by epoberezkin** [comment]
moved these commits to #3952

**Pull request closed without merging**
